services:
  web:
    container_name: Drone_Application
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 drones.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    mem_limit: 1G